# Generated by Django 4.0.4 on 2022-11-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_ingredientinrecipe_options_alter_tag_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/', verbose_name='Image'),
        ),
    ]
