# Generated by Django 4.0.4 on 2022-11-07 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_ingredientinrecipe_amount_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tag',
            name='unique_tag',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(max_length=150, verbose_name='Unit of measure'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='text',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, 'Minimum text size'), django.core.validators.MaxValueValidator(9999, 'Maximum text size')], verbose_name='Recipe description'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('#E26C2D', '#E26C2D'), ('#49B64E', '#49B64E'), ('#8775D2', '#8775D2')], max_length=7, unique=True, verbose_name='Color HEX-code'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Tag'),
        ),
    ]
