# Generated by Django 4.0.4 on 2022-11-08 18:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_remove_tag_unique_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='text',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(500, 'Maximum length of text')], verbose_name='Recipe description'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='The value entered is not a color in hex-format', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='Color hex-code'),
        ),
    ]
